### ISSUE TITLE
Create shipable product with github action if tag is set

### ISSUE THREAD

**Issue by dhcgn** [haevg-rz/TrustCenterSearchGui#10]
Create with Github actions a new shipable version if a tag is present
`dotnet publish -r win-x64 -c Release --self-contained true /p:useapphost=true`

See 
https://git-scm.com/book/en/v2/Git-Basics-Tagging
https://git-scm.com/book/de/v2/Git-Grundlagen-Tagging

**Comment by KaHBrat** [comment]
dotnet publish -r win-x64 -c Release --self-contained true /p:useapphost=true /p:PublishSingleFile=True

**Comment by dhcgn** [comment]
Sample implementation

https://github.com/haevg-rz/Planungsboard/blob/master/.github/workflows/publish.yml
https://github.com/haevg-rz/Planungsboard/blob/master/CONTRIBUTING.md
