### ISSUE TITLE
Core: Configuration

### ISSUE THREAD

**Issue by TobiasMeissner2000** [haevg-rz/TrustCenterSearchGui#7]
- [x] Write tests
- [x] Multiple https sources
- [x] Read config from AppData
- [x] Create empty config if missing
- [x] Refactore tests

**Comment by TobiasMeissner2000** [comment]
### Config structure:
{
	"Webpages": [
		"link1",
		"link2",
		"link3"
	]
}

**Comment by TobiasMeissner2000** [comment]
### Config structure:
{
	"Webpages": [
		"link1",
		"link2",
		"link3"
...
	]
}

**Comment by dhcgn** [comment]
- The meaning of `Webpages` is unclear.
- It would be nice to store some more information about the origin of the downloeded certs.

```
public class Config
{
	public List<TrustCenter> TrustCenters {get; set;}
}

public class TrustCenter
{
	public string Name {get; set;}
	public List<CertificateStore> CertificateStores {get; set;}
}

public class CertificateStore
{
	public  string Name {get; set;}
	public  List<string> Urls {get; set;}
}
```

![image](https://user-images.githubusercontent.com/6566207/76970034-89861f00-692b-11ea-8bfc-895af06d818f.png)

**Comment by TobiasMeissner2000** [comment]
- renamed "Webpages" into "TrustCenterURLs"
- more information will come in the next steps @dhcgn

**Comment by TobiasMeissner2000** [comment]
### New Config structure:
```
{
	"TrustCenters": [
			{
				"Name": "Example1",
				"TrustCenterURL": "link1"
			},
			{
				"Name": "Example2",
				"TrustCenterURL": "link2"
			},
			{
				"Name": "Example3",
				"TrustCenterURL": "link3"
			}
	]
}
```

**Comment by dhcgn** [comment]
Please close issues when work is done.
